WHICH OF THE FOLLOWING IS NOT A BENEFIT OF DEPLOYING EXCHANGE SERVERS AS VIRTUAL MACHINES?
MORE SECURE

WHICH AD COMPONENT IS A COLLECTION OF COMPUTERS THAT A Microsoft Windows NETWORK ADMINISTRATOR DEFINES?
DOMAINS

WHEN ENABLING POP3 OR IMAP4 WHICH SETTING ENABLES THE CONFIGURATION OF SECURE LOGON REQUIRING TLS?
AUTHENTICATION

WHAT REDUCES HOW OFTEN A MESSAGE IS SCANNED AS IT PROCEEDS THROUGH AN ORGANIZATION BY TAGGING SCANNED MESSAGES WITH THE VERSION OF THE ANTIVIRUS SOFTWARE THAT PERFORMED THE SCAN AND THE SCAN RESULTS?
ANTIVIRUS STAMPING

WHICH TROUBLESHOOTING STEP IN OUTLOOK CLIENT USES DNS HOST-NAME RESOLUTION TO RESOLVE THE NAME OF THE EXCHANGE SERVER TO ITS IP ADDRESS?
IDENTIFY THE NAME RESOLUTION ISSUES

WHERE DOES A WINDOWS 2008 R2 EDGE SERVER STORE ITS CONFIGURATION INFORMATION?
AD LDS

WHAT OPTION IS NOT PROVIDED BY A DIGITAL SIGNATURE?
AUTHORIZATION

FOR MOST ORGANIZATIONS, WHAT IS A CRITICAL PART OF THE NETWORK THAT PEOPLE RELY ON TO PERFORM THEIR JOBS?
MESSAGING

THE EXCHANGE CONTROL PANEL ALLOWS ALL MAILBOX USERS TO CONFIGURE MOST OF THEIR MAILBOX SETTINGS EXCEPT
MANAGE EXISTING MAILBOXES AND RBAC PERMISSIONS

WHICH SERVICE IS USED TO PROVIDE CONFIGURATION INFORMATION FOR THE CLIENT AND REPAIR EXCHANGE SERVER CONNECTION SETTINGS TO DISCOVER A MOVED MAILBOX?
AUTODISCOVER

WHICH TYPE OF MAILBOX CAN BE ASSIGNED TO A MEETING LOCATION OR AN ASSET SUCH AS A PROJECTOR?
RESOURCE

WHICH OPTION IS USED TO CONFIGURE RESOURCE MAILBOX SETTINGS AND CUSTOMIZE THE RESOURCE MAILBOX TO MEET AN ORGANIZATION'S NEEDS?
BOOKING POLICIES

WHICH STATEMENT IS CONSIDERED BEST PRACTICE FOR PUBLIC FOLDER DEPLOYMENT?
IN CASES OF LIMITED BANDWIDTH, SCHEDULE PUBLIC FOLDERS

UPON OBTAINING A NEW SERVER CERTIFICATE, WHERE IS IT INSTALLED?
CLIENT ACCESS

WHICH PROCESS IS USED TO CREATE AND UPDATE THE OABGEN SERVICE?
OFFLINE ADDRESS BOOK GENERATION

WHICH SERVER ROLE IN EXCHANGE SERVER 2010 PROVIDES A SECURE SMTP GATEWAY FOR ALL INCOMING AND OUTGOING EMAILS IN AN ORGANIZATION?
EDGE TRANSPORT

WHICH CMDLET WOULD BE USED TO LIST THE MEMBERS OF THE SALES GROUP?
GET-DISTRIBUTIONGROUPSALES

WHICH EXCHANGE MANAGEMENT CONSOLE PANE EXPOSES DIFFERENT ADMINISTRATIVE TASKS IN RESPONSE TO THE SELECTIONS MADE WITHIN THE RESULTS AND WORK PANES?
ACTIONS

WHICH ADDRESS POLICY WOULD BE CHECKED IF THE EMAIL ADDRESS POLICY IS TO BE APPLIED TO SECURITY GROUPS OR DISTRIBUTION GROUPS THAT HAVE BEEN MAIL-ENABLED?
MAIL-ENABLED GROUPS

WHAT ENABLES GRANULAR PERMISSIONS TO BE ASSIGNED TO ADMINISTRATORS, CLOSELY ALIGNING THE ROLES THAT ASSIGN USERS AND ADMINISTRATORS TO THE ACTUAL ROLES THEY HOLD WITHIN AN ORGANIZATION?
RBACs

WHICH RAID OPTION INCREASES FAULT TOLERANCE BY PLACING REDUNDANT COPIES OF DATA ON TWO DISKS?
1

WHAT IS IT CALLED WHEN THE PUBLIC KEY ENCRYPTS THE HASH VALUE THEREFORE A MESSAGE IS DIGITALLY SIGNED TO PREVENT ITS SENDER FROM DISOWNING THE MESSAGE?
NONREPUDIATION

WHICH TYPE OF RESOURCE MAILBOXES CAN YOU ASSIGN TO RESOURCES THAT ARE NOT LOCATION-SPECIFIC, SUCH AS PORTABLE COMPUTER PROJECTORS, MICROPHONES, OR COMPANY CARS?
EQUIPMENT

WHICH OPTION IS USED TO ASSIGN PERMISSION TO REVIEW ALL MESSAGES THAT ARE SENT TO THE DISTRIBUTION LIST?
MESSAGE MODERATION

WHICH EDGE TRANSPORT SERVER ROLE FUNCTIONALITY HELPS PREVENT SPAM MESSAGES AND VIRUSES FROM REACHING AN ORGANIZATION'S USERS BY USING A COLLECTION OF AGENTS THAT PROVIDE DIFFERENT LAYERS OF SPAM FILTERING AND VIRUS PROTECTION?
ANTIVIRUS AND ANTI-SPAM PROTECTION

IF MULTIPLE ACTIVE DIRECTORY SITES ARE ENABLED, THE ADMINISTRATOR CAN PROVIDE INTERNET ACCESS TO EACH SITE BY CONFIGURING AN EXTERNAL URL TO WHICH SERVER?
CLIENT ACCESS

WITHIN THE MESSAGE TRANSPORT IN EXCHANGE SERVER 2010 WHICH QUEUE STORES ALL MESSAGES ON A DISK UNTIL THE CATEGORIZER PROCESSES THEM FOR DELIVERY?
SUBMISSION

WHICH CMDLET WOULD BE USED TO DISPLAY INFORMATION FOR A NEW MAILBOX?
GET-MAILBOX

IN WHICH ACTIVE DIRECTORY PARTITION CAN CONFIGURATION INFORMATION FOR THE AD DS BE FOUND?
CONFIGURATION

WHICH OPTION WOULD BE CONFIGURED IN ACCEPTED DOMAINS TO ALLOW THE HUB TRANSPORT OR EDGE TRANSPORT SERVER TO ACCEPT THE EMAIL, BUT RELAY IT TO AN ALTERNATE SMTP SERVER?
EXTERNAL RELAY

WHICH TOOL AUTOMATICALLY EXAMINES AN EXCHANGE SERVER DEPLOYMENT AND DETERMINES WHETHER THE CONFIGURATION IS IN LINE WITH MICROSOFT BEST PRACTICES?
BEST PRACTICES ANALYZER

SRV RESOURCE RECORDS ARE WHICH TYPE OF RECORDS?
DNS

WHICH SERVICE WAS INTRODUCED IN EXCHANGE SERVER 2007 AS A FEATURE WHERE CLIENTS AUTOMATICALLY CONFIGURED THEIR PROFILES TO ACCESS EXCHANGE SERVER?
AUTODISCOVER

WHAT IS USED TO MANAGE MULTIPLE RECIPIENTS OR OBJECTS AT ONE TIME PRIMARILY THROUGH THE USE OF PIPING AND FILTERING?
EXCHANGE MANAGEMENT SHELL

WHAT ARE SMALL EXECUTABLE FILES WRITTEN IN MICROSOFT VISUAL C# OR ANY OTHER MICROSOFT .NET FRAMEWORK-COMPLIANT LANGUAGE CALLED?
SIMPLE CMDLETS

WHICH CERTIFICATES ARE THE MORE EXPENSIVE ALTERNATIVE WHEN CHOOSING A CERTIFICATION AUTHORITY?
PUBLIC

HOW IS OUTLOOK ANYWHERE CONFIGURED?
RPC OVER HTTP

HOW MANY NEW CMDLETS WERE ADDED TO THE EXCHANGE MANAGEMENT SHELL?
700

WHICH TWO ROLES IS BACK PRESSURE INSTALLED ON?
HUB TRANSPORT AND EDGE TRANSPORT

IN WHICH DIRECTORY ARE THE CONFIGURATION OPTIONS FOR BACK PRESSURE LOCATED?
BIN DIRECTORY

WHAT IS DONE BEFORE DEPLOYING MAILBOXES ON THE MAILBOX SERVER ROLE THAT INCLUDES CONFIGURING PERMISSIONS AT THE ORGANIZATIONAL AND SERVER LEVELS TO REDUCE THE EXCHANGE SERVERS' ATTACK SURFACE?
SECURE THE SERVER

WHICH FILTERING AGENT IS USED TO REDUCE SPAM AND VIRUSES ON THE EDGE TRANSPORT OR HUB TRANSPORT TO REDUCE THE SPREAD OF MALWARE ATTACHMENTS BEFORE THEY ENTER AN ORGANIZATION?
ATTACHMENT

WHICH EXCHANGE SERVER ROLE ENABLES CONNECTIONS FROM ALL AVAILABLE CLIENT PROTOCOLS TO THE EXCHANGE SERVER MAILBOXES?
CLIENT ACCESS

WHICH CONFIGURATION NODE WOULD BE USED TO ASSIGN VALUES TO THE MAILBOXES, DISTRIBUTION GROUPS, AND CONTACTS?
RECIPIENTS

WHICH COMMAND IS USED TO SPECIFY THE NAME GIVEN TO THE NEW EXCHANGE ORGANIZATION?
/ORGANIZATIONNAME

WHAT IS DEPLOYED ON THE HUB AND EDGE TRANSPORT SERVERS TO PROTECT AGAINST VIRUSES WITHIN EMAILS?
ANTI-VIRUS SOFTWARE

WHAT PROVIDES A SET OF EXTENSIONS TO THE BASIC IP PROTOCOL AND CAN BE USED TO ENCRYPT SERVER-TO-SERVER COMMUNICATIONS?
IPSEC

IN AN EXCHANGE SERVER MESSAGING ENVIRONMENT, WHERE MUST A HUB TRANSPORT SERVER ROLE BY DEPLOYED?
IN EACH ACTIVE DIRECTORY SITE WHERE A MAILBOX

WHAT SMTP STANDARD IS USED TO IMPLEMENT PUBLIC-KEY ENCRYPTION AND EMAIL MESSAGE SIGNATURES?
S/MIME

WHICH INFORMATION DEFINES THE TYPES OF OBJECTS AND ATTRIBUTES THAT CAN BE CREATED IN AD LDS?
SCHEMA
